/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author ing_a
 */
public class InterDireccion extends javax.swing.JFrame {

    
    public InterDireccion() {
        initComponents();
        DarBajaGrupo.setVisible(false);
        GruposExist.setVisible(false);
        NuevoGrupo.setVisible(false);
        DarAltaGrupo.setVisible(false);
        
        ApeMatAluPro.setVisible(false);
        ApeMatAluProtxt.setVisible(false);
        ApePatAluPro.setVisible(false);
        ApePatAluProtxt.setVisible(false);
        AsigGrupComboAluPro.setVisible(false);
        AsigGrupoAluPro.setVisible(false);
        DarAltaAlu.setVisible(false);
        NombresAluPro.setVisible(false);
        NombresAluProtxt.setVisible(false);
        ModifiAlu.setVisible(false);
        Cedula.setVisible(false);
        Cedulatxt.setVisible(false);
        ConsultaGrupo.setVisible(false);
        BuscaGrupo.setVisible(false);
        MensajeLista.setVisible(false);
        
        
        DarAltaPro.setVisible(false);
        ModifiPro.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JLabel();
        Grupos = new javax.swing.JLabel();
        Alumnos = new javax.swing.JLabel();
        profes = new javax.swing.JLabel();
        CambContra = new javax.swing.JLabel();
        NuevoGrupo = new javax.swing.JTextField();
        DarAltaGrupo = new javax.swing.JLabel();
        GruposExist = new javax.swing.JComboBox<>();
        DarBajaGrupo = new javax.swing.JLabel();
        ApePatAluPro = new javax.swing.JLabel();
        ApeMatAluPro = new javax.swing.JLabel();
        NombresAluPro = new javax.swing.JLabel();
        AsigGrupComboAluPro = new javax.swing.JComboBox<>();
        DarAltaAlu = new javax.swing.JLabel();
        ApePatAluProtxt = new javax.swing.JTextField();
        ApeMatAluProtxt = new javax.swing.JTextField();
        NombresAluProtxt = new javax.swing.JTextField();
        AsigGrupoAluPro = new javax.swing.JLabel();
        ModifiAlu = new javax.swing.JLabel();
        DarAltaPro = new javax.swing.JLabel();
        ModifiPro = new javax.swing.JLabel();
        Cedulatxt = new javax.swing.JTextField();
        Cedula = new javax.swing.JLabel();
        ConsultaGrupo = new javax.swing.JLabel();
        BuscaGrupo = new javax.swing.JLabel();
        MensajeLista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(560, 240));
        setMaximumSize(new java.awt.Dimension(850, 480));
        setMinimumSize(new java.awt.Dimension(850, 480));
        setPreferredSize(new java.awt.Dimension(850, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        jLabel1.setText("BIENVENIDO DIRECCION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        CerrarSesion.setText("CERRAR SESION");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        Grupos.setText("GRUPOS");
        Grupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GruposMouseClicked(evt);
            }
        });
        getContentPane().add(Grupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        Alumnos.setText("ALUMNOS");
        Alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlumnosMouseClicked(evt);
            }
        });
        getContentPane().add(Alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        profes.setText("PROFESORES");
        profes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profesMouseClicked(evt);
            }
        });
        getContentPane().add(profes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        CambContra.setText("CAMBIAR CONTRASEÑA");
        CambContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CambContraMouseClicked(evt);
            }
        });
        getContentPane().add(CambContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        NuevoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(NuevoGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 140, -1));

        DarAltaGrupo.setText("DAR DE ALTA GRUPO");
        DarAltaGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DarAltaGrupoMouseClicked(evt);
            }
        });
        getContentPane().add(DarAltaGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        GruposExist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GruposExist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GruposExistActionPerformed(evt);
            }
        });
        getContentPane().add(GruposExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 150, 20));

        DarBajaGrupo.setText("DAR DE BAJA GRUPO");
        DarBajaGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DarBajaGrupoMouseClicked(evt);
            }
        });
        getContentPane().add(DarBajaGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        ApePatAluPro.setText("APELLIDO PATERNO");
        getContentPane().add(ApePatAluPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        ApeMatAluPro.setText("APELLIDO MATERNO");
        getContentPane().add(ApeMatAluPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        NombresAluPro.setText("NOMBRE(S)");
        getContentPane().add(NombresAluPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        AsigGrupComboAluPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AsigGrupComboAluPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsigGrupComboAluProActionPerformed(evt);
            }
        });
        getContentPane().add(AsigGrupComboAluPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 130, -1));

        DarAltaAlu.setText("DAR DE ALTA ALUMNO");
        DarAltaAlu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DarAltaAluMouseClicked(evt);
            }
        });
        getContentPane().add(DarAltaAlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, 20));

        ApePatAluProtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApePatAluProtxtActionPerformed(evt);
            }
        });
        getContentPane().add(ApePatAluProtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 130, -1));

        ApeMatAluProtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApeMatAluProtxtActionPerformed(evt);
            }
        });
        getContentPane().add(ApeMatAluProtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 120, -1));

        NombresAluProtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombresAluProtxtActionPerformed(evt);
            }
        });
        getContentPane().add(NombresAluProtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 120, -1));

        AsigGrupoAluPro.setText("ASIGNAR GRUPO");
        getContentPane().add(AsigGrupoAluPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        ModifiAlu.setText("MODIFICAR ALUMNO");
        ModifiAlu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifiAluMouseClicked(evt);
            }
        });
        getContentPane().add(ModifiAlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        DarAltaPro.setText("DAR DE ALTA PROFESOR");
        DarAltaPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DarAltaProMouseClicked(evt);
            }
        });
        getContentPane().add(DarAltaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, 20));

        ModifiPro.setText("MODIFICAR PROFESOR");
        ModifiPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifiProMouseClicked(evt);
            }
        });
        getContentPane().add(ModifiPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        Cedulatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulatxtActionPerformed(evt);
            }
        });
        getContentPane().add(Cedulatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 150, -1));

        Cedula.setText("CEDULA PROFESIONAL");
        getContentPane().add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        ConsultaGrupo.setText("CONSULTAR GRUPO");
        ConsultaGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaGrupoMouseClicked(evt);
            }
        });
        getContentPane().add(ConsultaGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        BuscaGrupo.setText("BUSCA GRUPO");
        getContentPane().add(BuscaGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        MensajeLista.setText("Aqui debe aparecer la lista con los alumnos que pertenecen al grupo");
        getContentPane().add(MensajeLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        InterInicioSesion EsIn = new InterInicioSesion();
        EsIn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CerrarSesionMouseClicked

    private void GruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GruposMouseClicked
        DarBajaGrupo.setVisible(true);
        GruposExist.setVisible(true);
        DarAltaGrupo.setVisible(true);
        NuevoGrupo.setVisible(true);
        ConsultaGrupo.setVisible(true);
        BuscaGrupo.setVisible(true);
        
        ApeMatAluPro.setVisible(false);
        ApeMatAluProtxt.setVisible(false);
        ApePatAluPro.setVisible(false);
        ApePatAluProtxt.setVisible(false);
        AsigGrupComboAluPro.setVisible(false);
        AsigGrupoAluPro.setVisible(false);
        DarAltaAlu.setVisible(false);
        NombresAluPro.setVisible(false);
        NombresAluProtxt.setVisible(false);
        ModifiAlu.setVisible(false);
        MensajeLista.setVisible(false);
       
        DarAltaPro.setVisible(false);
        ModifiPro.setVisible(false);
        Cedula.setVisible(false);
        Cedulatxt.setVisible(false);
    }//GEN-LAST:event_GruposMouseClicked

    private void AlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlumnosMouseClicked
        ApeMatAluPro.setVisible(true);
        ApeMatAluProtxt.setVisible(true);
        ApePatAluPro.setVisible(true);
        ApePatAluProtxt.setVisible(true);
        AsigGrupComboAluPro.setVisible(true);
        AsigGrupoAluPro.setVisible(true);
        DarAltaAlu.setVisible(true);
        NombresAluPro.setVisible(true);
        NombresAluProtxt.setVisible(true);
        ModifiAlu.setVisible(true);
        
        DarAltaPro.setVisible(false);
        ModifiPro.setVisible(false);
        DarAltaPro.setVisible(false);
        MensajeLista.setVisible(false);
        
        DarAltaGrupo.setVisible(false);
        DarBajaGrupo.setVisible(false);
        GruposExist.setVisible(false);
        NuevoGrupo.setVisible(false);
        Cedula.setVisible(false);
        Cedulatxt.setVisible(false);
        ConsultaGrupo.setVisible(false);
        BuscaGrupo.setVisible(false);
    }//GEN-LAST:event_AlumnosMouseClicked

    private void profesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profesMouseClicked
        ApeMatAluPro.setVisible(true);
        ApeMatAluProtxt.setVisible(true);
        ApePatAluPro.setVisible(true);
        ApePatAluProtxt.setVisible(true);
        AsigGrupComboAluPro.setVisible(true);
        AsigGrupoAluPro.setVisible(true);
        DarAltaAlu.setVisible(true);
        NombresAluPro.setVisible(true);
        NombresAluProtxt.setVisible(true);
        Cedula.setVisible(true);
        Cedulatxt.setVisible(true);
        
        DarAltaPro.setVisible(true);
        ModifiPro.setVisible(true);
        DarAltaAlu.setVisible(false);
        ModifiAlu.setVisible(false);
        MensajeLista.setVisible(false);
        
        DarAltaGrupo.setVisible(false);
        DarBajaGrupo.setVisible(false);
        GruposExist.setVisible(false);
        NuevoGrupo.setVisible(false);
        ConsultaGrupo.setVisible(false);
        BuscaGrupo.setVisible(false);
    }//GEN-LAST:event_profesMouseClicked

    private void CambContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CambContraMouseClicked
        InterCambiarContra InCam = new InterCambiarContra();
        InCam.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CambContraMouseClicked

    private void DarAltaGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarAltaGrupoMouseClicked
        DarAltaGrupo.setVisible(false);
        DarBajaGrupo.setVisible(false);
        GruposExist.setVisible(false);
        NuevoGrupo.setVisible(false);
        ConsultaGrupo.setVisible(false);
        BuscaGrupo.setVisible(false);
        
    }//GEN-LAST:event_DarAltaGrupoMouseClicked

    private void GruposExistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GruposExistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GruposExistActionPerformed

    private void DarBajaGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarBajaGrupoMouseClicked
        DarAltaGrupo.setVisible(false);
        DarBajaGrupo.setVisible(false);
        GruposExist.setVisible(false);
        NuevoGrupo.setVisible(false);
        ConsultaGrupo.setVisible(false);
        BuscaGrupo.setVisible(false);
        MensajeLista.setVisible(false);
    }//GEN-LAST:event_DarBajaGrupoMouseClicked

    private void NuevoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoGrupoActionPerformed

    private void ApePatAluProtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApePatAluProtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApePatAluProtxtActionPerformed

    private void ApeMatAluProtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApeMatAluProtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApeMatAluProtxtActionPerformed

    private void NombresAluProtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombresAluProtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombresAluProtxtActionPerformed

    private void AsigGrupComboAluProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsigGrupComboAluProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsigGrupComboAluProActionPerformed

    private void DarAltaAluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarAltaAluMouseClicked
        ApeMatAluPro.setVisible(false);
        ApeMatAluProtxt.setVisible(false);
        ApePatAluPro.setVisible(false);
        ApePatAluProtxt.setVisible(false);
        AsigGrupComboAluPro.setVisible(false);
        AsigGrupoAluPro.setVisible(false);
        DarAltaAlu.setVisible(false);
        NombresAluPro.setVisible(false);
        NombresAluProtxt.setVisible(false);
        ModifiAlu.setVisible(false);
    }//GEN-LAST:event_DarAltaAluMouseClicked

    private void ModifiAluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifiAluMouseClicked
        InterModifiAlu InModiAlu = new InterModifiAlu();
        InModiAlu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ModifiAluMouseClicked

    private void DarAltaProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarAltaProMouseClicked
        ApeMatAluPro.setVisible(false);
        ApeMatAluProtxt.setVisible(false);
        ApePatAluPro.setVisible(false);
        ApePatAluProtxt.setVisible(false);
        AsigGrupComboAluPro.setVisible(false);
        AsigGrupoAluPro.setVisible(false);
        DarAltaAlu.setVisible(false);
        NombresAluPro.setVisible(false);
        NombresAluProtxt.setVisible(false);
        ModifiAlu.setVisible(false);
        DarAltaPro.setVisible(false);
        ModifiPro.setVisible(false);
        Cedula.setVisible(false);
        Cedulatxt.setVisible(false);
    }//GEN-LAST:event_DarAltaProMouseClicked

    private void ModifiProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifiProMouseClicked
        InterModiPro InModPro = new InterModiPro();
        InModPro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ModifiProMouseClicked

    private void CedulatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulatxtActionPerformed

    private void ConsultaGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaGrupoMouseClicked
        MensajeLista.setVisible(true);
        DarAltaGrupo.setVisible(false);
        NuevoGrupo.setVisible(false);
    }//GEN-LAST:event_ConsultaGrupoMouseClicked

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alumnos;
    private javax.swing.JLabel ApeMatAluPro;
    private javax.swing.JTextField ApeMatAluProtxt;
    private javax.swing.JLabel ApePatAluPro;
    private javax.swing.JTextField ApePatAluProtxt;
    private javax.swing.JComboBox<String> AsigGrupComboAluPro;
    private javax.swing.JLabel AsigGrupoAluPro;
    private javax.swing.JLabel BuscaGrupo;
    private javax.swing.JLabel CambContra;
    private javax.swing.JLabel Cedula;
    private javax.swing.JTextField Cedulatxt;
    private javax.swing.JLabel CerrarSesion;
    private javax.swing.JLabel ConsultaGrupo;
    private javax.swing.JLabel DarAltaAlu;
    private javax.swing.JLabel DarAltaGrupo;
    private javax.swing.JLabel DarAltaPro;
    private javax.swing.JLabel DarBajaGrupo;
    private javax.swing.JLabel Grupos;
    private javax.swing.JComboBox<String> GruposExist;
    private javax.swing.JLabel MensajeLista;
    private javax.swing.JLabel ModifiAlu;
    private javax.swing.JLabel ModifiPro;
    private javax.swing.JLabel NombresAluPro;
    private javax.swing.JTextField NombresAluProtxt;
    private javax.swing.JTextField NuevoGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel profes;
    // End of variables declaration//GEN-END:variables
}
