/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author ing_a
 */
public class InterTutor extends javax.swing.JFrame {

    /**
     * Creates new form EscolyTutor
     */
    public InterTutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CerrarSes = new javax.swing.JLabel();
        SoliSali = new javax.swing.JLabel();
        Emerg = new javax.swing.JLabel();
        ConfirLlega = new javax.swing.JLabel();
        InfoEstu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Estatustxt = new javax.swing.JTextField();
        CambiContra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(560, 240));
        setMaximumSize(new java.awt.Dimension(850, 480));
        setMinimumSize(new java.awt.Dimension(850, 480));
        setPreferredSize(new java.awt.Dimension(850, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 2, 24)); // NOI18N
        jLabel1.setText("BIENVENIDO TUTOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 47, -1, -1));

        CerrarSes.setText("CERRAR SESION");
        CerrarSes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesMouseClicked(evt);
            }
        });
        getContentPane().add(CerrarSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 24, -1, -1));

        SoliSali.setText("SOLICITAR SALIDA");
        SoliSali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoliSaliMouseClicked(evt);
            }
        });
        getContentPane().add(SoliSali, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        Emerg.setText("EMERGENCIA");
        Emerg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmergMouseClicked(evt);
            }
        });
        getContentPane().add(Emerg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        ConfirLlega.setText("CONFIRMAR LLEGADA");
        ConfirLlega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirLlegaMouseClicked(evt);
            }
        });
        getContentPane().add(ConfirLlega, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

        InfoEstu.setText("ESTUDIANTE");
        InfoEstu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfoEstuMouseClicked(evt);
            }
        });
        getContentPane().add(InfoEstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel2.setText("ESTATUS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        Estatustxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstatustxtActionPerformed(evt);
            }
        });
        getContentPane().add(Estatustxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 180, -1));

        CambiContra.setText("CAMBIAR CONTRASEÑA");
        CambiContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CambiContraMouseClicked(evt);
            }
        });
        getContentPane().add(CambiContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesMouseClicked
        InterInicioSesion EsIn = new InterInicioSesion();
        EsIn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CerrarSesMouseClicked

    private void InfoEstuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoEstuMouseClicked
        InterTutorEstudiante EsTutEst = new InterTutorEstudiante();
        EsTutEst.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InfoEstuMouseClicked

    private void SoliSaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoliSaliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SoliSaliMouseClicked

    private void EmergMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmergMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EmergMouseClicked

    private void ConfirLlegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirLlegaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirLlegaMouseClicked

    private void EstatustxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstatustxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstatustxtActionPerformed

    private void CambiContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CambiContraMouseClicked
        InterCambiarContra InCam = new InterCambiarContra();
        InCam.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CambiContraMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CambiContra;
    private javax.swing.JLabel CerrarSes;
    private javax.swing.JLabel ConfirLlega;
    private javax.swing.JLabel Emerg;
    private javax.swing.JTextField Estatustxt;
    private javax.swing.JLabel InfoEstu;
    private javax.swing.JLabel SoliSali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
