/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author ing_a
 */
public class InterCambiarContra extends javax.swing.JFrame {

    /**
     * Creates new form InterDireccionCambiarContra
     */
    public InterCambiarContra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ContraActual = new javax.swing.JTextField();
        NuevaContra = new javax.swing.JTextField();
        ConfirmarContra = new javax.swing.JTextField();
        CambiarContra = new javax.swing.JLabel();
        Regresa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(560, 240));
        setMaximumSize(new java.awt.Dimension(850, 480));
        setMinimumSize(new java.awt.Dimension(850, 480));
        setPreferredSize(new java.awt.Dimension(850, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        jLabel1.setText("CAMBIAR CONTRASEÑA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel2.setText("CONTRASEÑA ACTUAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel3.setText("NUEVA CONTRASEÑA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel4.setText("CONFIRMAR CONTRASEÑA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        ContraActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraActualActionPerformed(evt);
            }
        });
        getContentPane().add(ContraActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 180, 20));

        NuevaContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaContraActionPerformed(evt);
            }
        });
        getContentPane().add(NuevaContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 180, -1));

        ConfirmarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarContraActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 180, -1));

        CambiarContra.setText("CAMBIAR");
        CambiarContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CambiarContraMouseClicked(evt);
            }
        });
        getContentPane().add(CambiarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        Regresa.setText("REGRESAR");
        Regresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresaMouseClicked(evt);
            }
        });
        getContentPane().add(Regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContraActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraActualActionPerformed

    private void NuevaContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaContraActionPerformed

    private void ConfirmarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmarContraActionPerformed

    private void CambiarContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CambiarContraMouseClicked
        InterInicioSesion Inses = new InterInicioSesion();
        Inses.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CambiarContraMouseClicked

    private void RegresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresaMouseClicked
        InterInicioSesion Inses = new InterInicioSesion();
        Inses.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresaMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CambiarContra;
    private javax.swing.JTextField ConfirmarContra;
    private javax.swing.JTextField ContraActual;
    private javax.swing.JTextField NuevaContra;
    private javax.swing.JLabel Regresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
