/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author ing_a
 */
public class InterModifiAlu extends javax.swing.JFrame {

    /**
     * Creates new form InterModifiAlu
     */
    public InterModifiAlu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Regresar = new javax.swing.JLabel();
        BCApePatAlu = new javax.swing.JLabel();
        BCApeMatAlu = new javax.swing.JLabel();
        BCNombres = new javax.swing.JLabel();
        BCGrupCombo = new javax.swing.JComboBox<>();
        BCApePatAlutxt = new javax.swing.JTextField();
        BCApeMatAlutxt = new javax.swing.JTextField();
        BCNombrestxt = new javax.swing.JTextField();
        BCSeleccionGrupo = new javax.swing.JLabel();
        ActuAlu = new javax.swing.JLabel();
        DarBajaAlu = new javax.swing.JLabel();
        ApePatTut = new javax.swing.JTextField();
        ApeMatTut = new javax.swing.JTextField();
        NombreTut = new javax.swing.JTextField();
        CorreoTut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ApePatTut1 = new javax.swing.JTextField();
        ApeMatTut1 = new javax.swing.JTextField();
        NombreTut1 = new javax.swing.JTextField();
        CorreoTut1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ApePatTut2 = new javax.swing.JTextField();
        ApeMatTut2 = new javax.swing.JTextField();
        NombreTut2 = new javax.swing.JTextField();
        CorreoTut2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(560, 240));
        setMaximumSize(new java.awt.Dimension(850, 480));
        setMinimumSize(new java.awt.Dimension(850, 480));
        setPreferredSize(new java.awt.Dimension(850, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        jLabel1.setText("MODIFICAR ALUMNO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        Regresar.setText("REGRESAR");
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        BCApePatAlu.setText("APELLIDO PATERNO");
        getContentPane().add(BCApePatAlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        BCApeMatAlu.setText("APELLIDO MATERNO");
        getContentPane().add(BCApeMatAlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        BCNombres.setText("NOMBRE(S)");
        getContentPane().add(BCNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        BCGrupCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BCGrupCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCGrupComboActionPerformed(evt);
            }
        });
        getContentPane().add(BCGrupCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 130, -1));

        BCApePatAlutxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCApePatAlutxtActionPerformed(evt);
            }
        });
        getContentPane().add(BCApePatAlutxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 130, -1));

        BCApeMatAlutxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCApeMatAlutxtActionPerformed(evt);
            }
        });
        getContentPane().add(BCApeMatAlutxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 120, -1));

        BCNombrestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCNombrestxtActionPerformed(evt);
            }
        });
        getContentPane().add(BCNombrestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 120, -1));

        BCSeleccionGrupo.setText("SELECCIONA GRUPO");
        getContentPane().add(BCSeleccionGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        ActuAlu.setText("ACTUALIZAR");
        ActuAlu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActuAluMouseClicked(evt);
            }
        });
        getContentPane().add(ActuAlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        DarBajaAlu.setText("DAR DE BAJA");
        DarBajaAlu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DarBajaAluMouseClicked(evt);
            }
        });
        getContentPane().add(DarBajaAlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        ApePatTut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApePatTutActionPerformed(evt);
            }
        });
        getContentPane().add(ApePatTut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 130, -1));

        ApeMatTut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApeMatTutActionPerformed(evt);
            }
        });
        getContentPane().add(ApeMatTut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 140, -1));

        NombreTut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTutActionPerformed(evt);
            }
        });
        getContentPane().add(NombreTut, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 130, -1));

        CorreoTut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoTutActionPerformed(evt);
            }
        });
        getContentPane().add(CorreoTut, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 230, -1));

        jLabel2.setText("TUTOR 3");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jLabel3.setText("APELLIDO PATERNO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel4.setText("APELLIDO MATERNO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel5.setText("NOMBRE(S)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        jLabel6.setText("CORREO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, -1));

        ApePatTut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApePatTut1ActionPerformed(evt);
            }
        });
        getContentPane().add(ApePatTut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 130, -1));

        ApeMatTut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApeMatTut1ActionPerformed(evt);
            }
        });
        getContentPane().add(ApeMatTut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 140, -1));

        NombreTut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTut1ActionPerformed(evt);
            }
        });
        getContentPane().add(NombreTut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 130, -1));

        CorreoTut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoTut1ActionPerformed(evt);
            }
        });
        getContentPane().add(CorreoTut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 230, -1));

        jLabel7.setText("APELLIDO PATERNO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel8.setText("APELLIDO MATERNO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jLabel9.setText("NOMBRE(S)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jLabel10.setText("CORREO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, -1));

        ApePatTut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApePatTut2ActionPerformed(evt);
            }
        });
        getContentPane().add(ApePatTut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 130, -1));

        ApeMatTut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApeMatTut2ActionPerformed(evt);
            }
        });
        getContentPane().add(ApeMatTut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 140, -1));

        NombreTut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTut2ActionPerformed(evt);
            }
        });
        getContentPane().add(NombreTut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 130, -1));

        CorreoTut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoTut2ActionPerformed(evt);
            }
        });
        getContentPane().add(CorreoTut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 230, -1));

        jLabel11.setText("APELLIDO PATERNO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        jLabel12.setText("APELLIDO MATERNO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        jLabel13.setText("NOMBRE(S)");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        jLabel14.setText("CORREO");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, -1, -1));

        jLabel15.setText("TUTOR 1");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jLabel16.setText("TUTOR 2");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        InterDireccion Indi = new InterDireccion();
        Indi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarMouseClicked

    private void BCGrupComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCGrupComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BCGrupComboActionPerformed

    private void BCApePatAlutxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCApePatAlutxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BCApePatAlutxtActionPerformed

    private void BCApeMatAlutxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCApeMatAlutxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BCApeMatAlutxtActionPerformed

    private void BCNombrestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCNombrestxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BCNombrestxtActionPerformed

    private void DarBajaAluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarBajaAluMouseClicked
        BCApeMatAlu.setVisible(false);
        BCApeMatAlutxt.setVisible(false);
        BCApePatAlu.setVisible(false);
        BCApePatAlutxt.setVisible(false);
        BCGrupCombo.setVisible(false);
        BCNombres.setVisible(false);
        BCNombrestxt.setVisible(false);
        BCSeleccionGrupo.setVisible(false);
        DarBajaAlu.setVisible(false);
        ActuAlu.setVisible(false);
        
        InterDireccion Indi = new InterDireccion();
        Indi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DarBajaAluMouseClicked

    private void ActuAluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActuAluMouseClicked
        
    }//GEN-LAST:event_ActuAluMouseClicked

    private void NombreTutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTutActionPerformed

    private void CorreoTutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoTutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoTutActionPerformed

    private void ApePatTutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApePatTutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApePatTutActionPerformed

    private void ApeMatTutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApeMatTutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApeMatTutActionPerformed

    private void ApePatTut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApePatTut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApePatTut1ActionPerformed

    private void ApeMatTut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApeMatTut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApeMatTut1ActionPerformed

    private void NombreTut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTut1ActionPerformed

    private void CorreoTut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoTut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoTut1ActionPerformed

    private void ApePatTut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApePatTut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApePatTut2ActionPerformed

    private void ApeMatTut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApeMatTut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApeMatTut2ActionPerformed

    private void NombreTut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTut2ActionPerformed

    private void CorreoTut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoTut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoTut2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActuAlu;
    private javax.swing.JTextField ApeMatTut;
    private javax.swing.JTextField ApeMatTut1;
    private javax.swing.JTextField ApeMatTut2;
    private javax.swing.JTextField ApePatTut;
    private javax.swing.JTextField ApePatTut1;
    private javax.swing.JTextField ApePatTut2;
    private javax.swing.JLabel BCApeMatAlu;
    private javax.swing.JTextField BCApeMatAlutxt;
    private javax.swing.JLabel BCApePatAlu;
    private javax.swing.JTextField BCApePatAlutxt;
    private javax.swing.JComboBox<String> BCGrupCombo;
    private javax.swing.JLabel BCNombres;
    private javax.swing.JTextField BCNombrestxt;
    private javax.swing.JLabel BCSeleccionGrupo;
    private javax.swing.JTextField CorreoTut;
    private javax.swing.JTextField CorreoTut1;
    private javax.swing.JTextField CorreoTut2;
    private javax.swing.JLabel DarBajaAlu;
    private javax.swing.JTextField NombreTut;
    private javax.swing.JTextField NombreTut1;
    private javax.swing.JTextField NombreTut2;
    private javax.swing.JLabel Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
