/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author ing_a
 */
public class InterProfesor extends javax.swing.JFrame {

    /**
     * Creates new form EscolyProfesor
     */
    public InterProfesor() {
        initComponents();
        ListaAlu.setVisible(false);
        ListaSoli.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ListaAlum = new javax.swing.JLabel();
        Solicitud = new javax.swing.JLabel();
        CerrarSesi = new javax.swing.JLabel();
        CamContra = new javax.swing.JLabel();
        ListaAlu = new javax.swing.JLabel();
        ListaSoli = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(560, 240));
        setMaximumSize(new java.awt.Dimension(850, 480));
        setMinimumSize(new java.awt.Dimension(850, 480));
        setPreferredSize(new java.awt.Dimension(850, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        jLabel1.setText("BIENVENIDO PROFESOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        ListaAlum.setText("LISTA DE ALUMNOS");
        ListaAlum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaAlumMouseClicked(evt);
            }
        });
        getContentPane().add(ListaAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        Solicitud.setText("SOLICITUDES DE SALIDAS");
        Solicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SolicitudMouseClicked(evt);
            }
        });
        getContentPane().add(Solicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        CerrarSesi.setText("CERRAR SESION");
        CerrarSesi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesiMouseClicked(evt);
            }
        });
        getContentPane().add(CerrarSesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        CamContra.setText("CAMBIAR CONTRASEÑA");
        CamContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CamContraMouseClicked(evt);
            }
        });
        getContentPane().add(CamContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        ListaAlu.setText("AQUI SE DEBE MOSTRAR LA LISTA DE ALUMNOS");
        getContentPane().add(ListaAlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        ListaSoli.setText("AQUI SE DEBE MOSTRAR LA LISTA DE SOLICITUDES");
        getContentPane().add(ListaSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaAlumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaAlumMouseClicked
        ListaAlu.setVisible(true);
        ListaSoli.setVisible(false);
    }//GEN-LAST:event_ListaAlumMouseClicked

    private void SolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SolicitudMouseClicked
        ListaSoli.setVisible(true);
        ListaAlu.setVisible(false);
    }//GEN-LAST:event_SolicitudMouseClicked

    private void CerrarSesiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesiMouseClicked
        InterInicioSesion EsIn = new InterInicioSesion();
        EsIn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CerrarSesiMouseClicked

    private void CamContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CamContraMouseClicked
        InterCambiarContra InCam = new InterCambiarContra();
        InCam.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CamContraMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CamContra;
    private javax.swing.JLabel CerrarSesi;
    private javax.swing.JLabel ListaAlu;
    private javax.swing.JLabel ListaAlum;
    private javax.swing.JLabel ListaSoli;
    private javax.swing.JLabel Solicitud;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
