/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author ing_a
 */
public class InterModiPro extends javax.swing.JFrame {

    /**
     * Creates new form InterModiPro
     */
    public InterModiPro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regresar = new javax.swing.JLabel();
        ApePatProtxt = new javax.swing.JTextField();
        ApePatAluPro = new javax.swing.JLabel();
        ApeMatAluPro = new javax.swing.JLabel();
        ApeMatProtxt = new javax.swing.JTextField();
        NombresAluPro = new javax.swing.JLabel();
        NombresProtxt = new javax.swing.JTextField();
        AsigGrupComboPro = new javax.swing.JComboBox<>();
        AsigGrupoAluPro = new javax.swing.JLabel();
        ACTU = new javax.swing.JLabel();
        ELI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(560, 240));
        setMaximumSize(new java.awt.Dimension(850, 480));
        setMinimumSize(new java.awt.Dimension(850, 480));
        setPreferredSize(new java.awt.Dimension(850, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        jLabel1.setText("MODIFICAR PROFESOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        regresar.setText("REGRESAR");
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        ApePatProtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApePatProtxtActionPerformed(evt);
            }
        });
        getContentPane().add(ApePatProtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 130, -1));

        ApePatAluPro.setText("APELLIDO PATERNO");
        getContentPane().add(ApePatAluPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        ApeMatAluPro.setText("APELLIDO MATERNO");
        getContentPane().add(ApeMatAluPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        ApeMatProtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApeMatProtxtActionPerformed(evt);
            }
        });
        getContentPane().add(ApeMatProtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 120, -1));

        NombresAluPro.setText("NOMBRE(S)");
        getContentPane().add(NombresAluPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        NombresProtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombresProtxtActionPerformed(evt);
            }
        });
        getContentPane().add(NombresProtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 120, -1));

        AsigGrupComboPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AsigGrupComboPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsigGrupComboProActionPerformed(evt);
            }
        });
        getContentPane().add(AsigGrupComboPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 130, -1));

        AsigGrupoAluPro.setText("CAMBIAR GRUPO");
        getContentPane().add(AsigGrupoAluPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        ACTU.setText("ACTUALIZAR");
        ACTU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACTUMouseClicked(evt);
            }
        });
        getContentPane().add(ACTU, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        ELI.setText("ELIMINAR");
        ELI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ELIMouseClicked(evt);
            }
        });
        getContentPane().add(ELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        InterDireccion Indi = new InterDireccion();
        Indi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarMouseClicked

    private void ApePatProtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApePatProtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApePatProtxtActionPerformed

    private void ApeMatProtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApeMatProtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApeMatProtxtActionPerformed

    private void NombresProtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombresProtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombresProtxtActionPerformed

    private void AsigGrupComboProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsigGrupComboProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsigGrupComboProActionPerformed

    private void ACTUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACTUMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ACTUMouseClicked

    private void ELIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ELIMouseClicked
        InterDireccion InDi = new InterDireccion();
        InDi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ELIMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACTU;
    private javax.swing.JLabel ApeMatAluPro;
    private javax.swing.JTextField ApeMatProtxt;
    private javax.swing.JLabel ApePatAluPro;
    private javax.swing.JTextField ApePatProtxt;
    private javax.swing.JComboBox<String> AsigGrupComboPro;
    private javax.swing.JLabel AsigGrupoAluPro;
    private javax.swing.JLabel ELI;
    private javax.swing.JLabel NombresAluPro;
    private javax.swing.JTextField NombresProtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel regresar;
    // End of variables declaration//GEN-END:variables
}
